"use client";

import Link from "next/link";
import { ShoppingBag, Trash2 } from "lucide-react";
import { useStore } from "@/context/store-context";
import { Price, priceDetails, QuantityPicker } from "@/components/shared";

export function CartPage() {
  const { cart, updateQuantity, removeFromCart } = useStore();
  const details = priceDetails(cart);
  if (!cart.length) return <div className="mx-auto max-w-4xl px-4 py-24 text-center"><ShoppingBag size={38} className="mx-auto" /><h1 className="mt-5 text-3xl font-black">Your bag is empty</h1><p className="mt-3 text-zinc-500">Fill it with pieces you’ll return to again and again.</p><Link href="/category/all" className="mt-7 inline-block rounded-xl bg-zinc-950 px-6 py-3 text-xs font-bold tracking-[0.12em] text-white">EXPLORE PRODUCTS</Link></div>;
  return <div className="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8"><h1 className="text-4xl font-black tracking-[-0.06em]">Your bag <span className="text-zinc-400">({cart.length})</span></h1><div className="mt-8 grid gap-8 lg:grid-cols-[1fr_360px]"><section className="divide-y divide-zinc-200 rounded-2xl border border-zinc-200 bg-white px-5 sm:px-6">{cart.map((item) => <article className="flex gap-4 py-5" key={`${item.id}-${item.size}-${item.color}`}><Link href={`/product/${item.id}`} className="h-28 w-24 shrink-0 overflow-hidden rounded-lg bg-zinc-100"><img src={item.image} alt={item.name} className="h-full w-full object-cover grayscale" /></Link><div className="min-w-0 flex-1"><div className="flex justify-between gap-3"><div><p className="text-xs font-medium uppercase tracking-wider text-zinc-400">{item.brand}</p><Link href={`/product/${item.id}`} className="mt-1 block font-bold hover:underline">{item.name}</Link><p className="mt-1 text-xs text-zinc-500">Size: {item.size} · Color: {item.color}</p></div><button onClick={() => removeFromCart(item.id, item.size, item.color)} className="h-fit p-1 text-zinc-400 hover:text-zinc-950" aria-label={`Remove ${item.name}`}><Trash2 size={18} /></button></div><div className="mt-4 flex items-center justify-between"><QuantityPicker quantity={item.quantity} onChange={(quantity) => updateQuantity(item.id, quantity, item.size, item.color)} /><p className="font-bold"><Price value={item.price * item.quantity} /></p></div></div></article>)}</section><OrderDetails details={details} /></div><Link href="/category/all" className="mt-7 inline-block text-sm font-semibold underline">← Continue shopping</Link></div>;
}

export function OrderDetails({ details, action = true }: { details: ReturnType<typeof priceDetails>; action?: boolean }) { return <aside className="h-fit rounded-2xl border border-zinc-200 bg-white p-6"><h2 className="font-bold">Price details</h2><div className="mt-5 space-y-3 text-sm text-zinc-600"><p className="flex justify-between"><span>Subtotal</span><span><Price value={details.subtotal} /></span></p><p className="flex justify-between"><span>Shipping</span><span>{details.shipping ? <Price value={details.shipping} /> : "Free"}</span></p><p className="flex justify-between"><span>Tax (6%)</span><span><Price value={details.tax} /></span></p><p className="flex justify-between border-t border-zinc-200 pt-3 font-bold text-zinc-950"><span>Total</span><span><Price value={details.total} /></span></p></div>{action && <Link href="/checkout" className="mt-6 block rounded-xl bg-zinc-950 py-4 text-center text-xs font-bold tracking-[0.12em] text-white hover:bg-zinc-700">PROCEED TO CHECKOUT</Link>}</aside>; }
